### ISSUE TITLE
Sass 常见写法

### ISSUE THREAD

**Issue by Moonlightg** [Moonlightg/mb#10]
### 基础
> 变量与选择器

变量的定义一般以$开头，某个变量的作用域仅限于他们定义的层级以及子层级。如果变量是定义在所有嵌套选择器之外的，那么他们可以在各处被调用。

```scss
$color1: #aeaeae;
.div{
   background-color: $color1;
}
```
输出
```scss
.div {
  background-color: #aeaeae;
}
```
> 嵌套引用
```scss
$side: top;
$radius: 10px;
.round-#{$side} {
  border-#{$side}-radius: $radius;
  -moz-border-#{$side}-radius: $radius;
  -webkit-border-#{$side}-radiux: $radius;
}
```
输出
```scss
.round-top {
  border-top-radius: 10px;
  -moz-border-top-radius: 10px;
  -webkit-border-top-radiux: 10px;
}
```
