### ISSUE TITLE
Flex 布局：语法篇

### ISSUE THREAD

**Issue by Moonlightg** [Moonlightg/mb#13]
### 网页布局（layout）是 CSS 的一个重点应用
布局的传统解决方案，基于[`盒状模型`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)，依赖[` display `](https://developer.mozilla.org/en-US/docs/Web/CSS/display)属性 +[ `position`](https://developer.mozilla.org/en-US/docs/Web/CSS/position)属性 + [`float`](https://developer.mozilla.org/en-US/docs/Web/CSS/float)属性。它对于那些特殊布局非常不方便，比如，`垂直居中`就不容易实现。

> 兼容性
![image](https://user-images.githubusercontent.com/14285531/30790116-9b06237e-a1dc-11e7-8513-ce91bdb9c56f.png)

## 一、什么是Flex 布局？
Flex 是 Flexible Box 的缩写，意为"弹性布局"，用来为盒状模型提供最大的灵活性。
任何一个容器都可以指定为 Flex 布局。
```css
.box{
  display: flex;
}
```
行内元素也可以使用 Flex 布局。
```css
.box{
  display: inline-flex;
}
```
Webkit 内核的浏览器，必须加上-webkit前缀。
```css
.box{
  display: -webkit-flex; /* Safari */
  display: flex;
}
```
注意，设为 Flex 布局以后，子元素的`float`、`clear`和`vertical-align`属性将失效。
