### ISSUE TITLE
CSS3 画常用图标 

### ISSUE THREAD

**Issue by Moonlightg** [Moonlightg/mb#16]
### 画勾和叉
> 叉
```html
<i class="icon-fork"></i>
```
```css
.icon-fork{ 
    display: inline-block; 
    width: 20px;
    height:5px;
    background: red;
    line-height: 0;
    font-size:0;
    vertical-align: middle;
    -webkit-transform: rotate(45deg);
}
.icon-fork:after{
    content:'/';
    display:block;
    width: 20px;
    height:5px;
    background: red;
    -webkit-transform: rotate(-90deg);
}
```

> √勾
```html
<i class="icon-ok"></i>
```
```css
.icon-ok{ 
    display: inline-block; 
    width: 10px;
    height:5px;
    background: red;
    line-height: 0;
    font-size:0;
    vertical-align: middle;
    -webkit-transform: rotate(45deg);
}
.icon-ok:after{
    content:'/';
    display:block;
    width: 20px;
    height:5px;
    background: red;
   -webkit-transform: rotate(-90deg) translateY(-50%) translateX(50%);
}
```
