### ISSUE TITLE
vue,封装全局弹出组件 - ActionSheet

### ISSUE THREAD

**Issue by Moonlightg** [Moonlightg/mb#38]
### 根目录新建 ActionSheet.vue
```vue
<template>
  <div v-if="actionSheet.show || actionSheet.hidden" class="actionSheet" :class="{'show': actionSheet.show,'hidden': actionSheet.hidden}">
    <!--遮罩层-->
    <div class="actionSheet_mask" v-on:click="out()"></div>
    <!--主体-->
    <div class="actionSheet_content">
      <slot />
    </div>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        actionSheet: {
          show: false,
          hidden: false,
          key: this.asKey
        }
      }
    },
    props: {
      asKey: {
        type: String,
        required: true
      },
      hideTime: {
        type: Number,
        required: false
      },
      onHide: {
        type: Function,
        required: false
      }
    },
    methods: {
      // 点击遮罩时隐藏操作表
      out () {
        this.$events.emit('hideActionSheet', this.actionSheet.key)
      }
    },
    created () {
      this.$events.on('showActionSheet', (key) => {
        if (key === this.actionSheet.key) {
          this.actionSheet.show = true
          this.actionSheet.hidden = false
        }
      })
      this.$events.on('hideActionSheet', (key) => {
        if (key === this.actionSheet.key) {
          this.onHide && this.onHide()
          this.actionSheet.show = false
          this.actionSheet.hidden = true
          setTimeout(() => {
            this.actionSheet.show = false
            this.actionSheet.hidden = false
          }, this.hideTime || 600)
        }
      })
    }
  }
</script>
```

### 创建plugins.js
目录:src>utils>plugins.js
```js
import _ from 'lodash'

export const ActionSheetPlugin = {
  install: function (Vue, option) {
    // 注入组件
    Vue.mixin({
      mounted: function () {
        var self = this
        this.$events.on('toggle', (name, value) => {
          if (_.has(self, name)) {
            _.set(self, name, value)
          }
        })
      },
      methods: {
        showActionSheet (key) {
          this.$events.emit('showActionSheet', key)
        },
        hideActionSheet (key) {
          this.$events.emit('hideActionSheet', key)
        }
      }
    })
  }
}
```

### 安装vue-events
```
cnpm install vue-events --save
```

### main.js引入
```js
import VueEvents from 'vue-events'
import ActionSheet from './ActionSheet'
import {ActionSheetPlugin} from './utils/plugins'

Vue.use(VueEvents)

Vue.use(ActionSheetPlugin)

Vue.component('action-sheet', ActionSheet)

```

### 页面使用<action-sheet></action-sheet>组件

```vue
<template>
  <div @click="showGoodsQuotePrice">Click Me</div>
  <!--组件引用-->
  <action-sheet asKey="goodsQuotePrice">
     <p>11111111111</p>
     <p>11111111111</p>
     <p>11111111111</p>
     <p>11111111111</p>
     <p>11111111111</p>
  </action-sheet>
</template>
<script>

export default {
  components: {
  },
  data () {
    return {}
  },
  methods: {
    // 让操作表显示调用这个方法
    showGoodsQuotePrice () {
      this.showActionSheet('goodsQuotePrice')
    },
    hideGoodsQuotePrice () {
      this.hideActionSheet('goodsQuotePrice')
    }
  }
}
</script>
```
### transition.less,actionSheet.less

```less
// transition.less
.transform(@transform) {
  -webkit-transform: @transform; /* Safari 和 Chrome */
     -moz-transform: @transform; /* Firefox */
      -ms-transform: @transform; /* IE 9 */
       -o-transform: @transform; /* Opera */
          transform: @transform;
}

.transition(@transition) {
  -webkit-transition: @transition;
     -moz-transition: @transition;
      -ms-transition: @transition;
       -o-transition: @transition;
          transition: @transition;
}

// Animations
.animation(@animation) {
  animation: @animation;
  -webkit-animation: @animation;
       -o-animation: @animation;
}
.animation-name(@name) {
  animation-name: @name;
  -webkit-animation-name: @name;
}
.animation-duration(@duration) {
  animation-duration: @duration;
  -webkit-animation-duration: @duration;
}
.animation-timing-function(@timing-function) {
  animation-timing-function: @timing-function;
  -webkit-animation-timing-function: @timing-function;
}
.animation-delay(@delay) {
  animation-delay: @delay;
  -webkit-animation-delay: @delay;
}
.animation-iteration-count(@iteration-count) {
  animation-iteration-count: @iteration-count;
  -webkit-animation-iteration-count: @iteration-count;
}
.animation-direction(@direction) {
  animation-direction: @direction;
  -webkit-animation-direction: @direction;
}
.animation-fill-mode(@fill-mode) {
  animation-fill-mode: @fill-mode;
  -webkit-animation-fill-mode: @fill-mode;
}

.will_transform {
  //will-change: transform, opacity;
  transform: translateZ(0);
}


.fades(@fillmode, @direction, @time: .35s) {
  .will_transform;
  .animation(~"fade@{fillmode}@{direction}" @time cubic-bezier(.25,.8,.25,1) .05s forwards);
}

.hiddens(@fillmode, @time: .35s) {
  .will_transform;
  .animation(~"@{fillmode}" @time cubic-bezier(.25,.8,.25,1) .05s forwards);
}

/*-- fade out bottom--*/
.keyframes(@name, @rules) {

  @keyframes @name {
    @rules();
  }

  @-webkit-keyframes @name {
    @rules();
  }

  @-moz-keyframes @name {
    @rules();
  }

  @-ms-keyframes @name {
    @rules();
  }

  @-o-keyframes @name {
    @rules();
  }
}

// 从底部淡出
.keyframes(fadeoutbottom, {
    0% {
      .transform(translate3d(0, 0, 0));
    }
    100% {
      .transform(translate3d(0, 100%, 0));
    }
});

// 从底部淡入
.keyframes(fadeinbottom, {
    from {
      opacity: 0;
      .transform(translate3d(0, 100%, 0));
    }
    to {
      opacity: 1;
      .transform(translate3d(0, 0, 0));
    }
});

// 从顶部淡出
.keyframes(fadeouttop, {
    0% {
      .transform(translate3d(0, 0, 0));
    }
    100% {
      .transform(translate3d(0, -100%, 0));
    }
});

// 从顶部淡入
.keyframes(fadeintop, {
    0% {
      .transform(translate3d(0, -100%, 0));
    }
    100% {
      .transform(translate3d(0, 0, 0));
    }
});

// 从左边淡出
.keyframes(fadeoutleft, {
    0% {
      .transform(translate3d(0, 0, 0));
    }
    100% {
      .transform(translate3d(-100%, 0, 0));
    }
});

// 从左边淡入
.keyframes(fadeinleft, {
    0% {
      .transform(translate3d(-100%, 0, 0));
    }
    100% {
      .transform(translate3d(0, 0, 0));
    }
});

// 从右边淡出
.keyframes(fadeoutright, {
    0% {
      .transform(translate3d(0, 0, 0));
      opacity: 1;
    }
    100% {
      .transform(translate3d(100%, 0, 0));
      opacity: 0;
    }
});

// 从右边淡入
.keyframes(fadeinright, {
    0% {
      .transform(translate3d(100%, 0, 0));
      opacity: 0;
    }
    100% {
      .transform(translate3d(0, 0, 0));
      opacity: 1;
    }
});

// 从中间淡出
.keyframes(fadeoutcenter, {
    0% {
      .transform(scale3d(1, 1, 1));
    }
    100% {
      .transform(scale3d(0, 0, 0));
    }
});

// 从中间淡入
.keyframes(fadeincenter, {
    0% {
      .transform(scale3d(0, 0, 0));
    }
    100% {
      .transform(scale3d(1, 1, 1));
    }
});

// 淡出
.keyframes(fadeout, {
    0% {
      opacity: 1;
    }
    100% {
      opacity: 0;
    }
});

// 淡入
.keyframes(fadein, {
    0% {
      opacity: 0;
      visibility: visible;
    }
    100% {
      opacity: 1;
      visibility: visible;
    }
});

// 隐藏
.keyframes(hidden, {
    100% {
      display: none;
    }
});

// 显示
.keyframes(show, {
    100% {
      visibility: visible;
    }
});

```

```less
// actionSheet.less
@actionSheetAlpha:   rgba(0, 0, 0, .5);

// 默认效果从下往上

.actionSheet{
  //整体铺满屏幕 默认隐藏
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 200;
  visibility: hidden;
  // 透明背景
  .actionSheet_mask{
    position: absolute;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: @actionSheetAlpha;
  }
  // 内容
  .actionSheet_content {
    background-color: #fff;
    position: absolute;
    z-index: 1;
    width: 100%;
    .actionSheet_scroll {
      max-height: ~"calc(100vh - 15rem)";
      overflow: auto;
      .will_transform;
      .touch();
    }
  }
  // 显示
  &.show {
    .hiddens(show, @fadein_time);
    // 遮罩层
    .actionSheet_mask {
      .fades(in, '', @fadein_time);
    }
    // 内容
    .actionSheet_content {
      .fades(in, bottom, @fadein_time);
    }
  }
  // 隐藏
  &.hidden {
    //visibility: visible;
    .hiddens(show, @fadein_time);
    // 遮罩层
    .actionSheet_mask {
      .fades(out, '', @fadeout_time);
    }
    // 内容
    .actionSheet_content {
      .fades(out, bottom, @fadeout_time);
    }
  }
}
```
