### ISSUE TITLE
响应式布局方案选择

### ISSUE THREAD

**Issue by Moonlightg** [Moonlightg/mb#45]
### 可选择的方案
* CSS3 Media Query（推荐）：媒体查询，兼容到IE9+，但可以通过插件兼容IE6-8
* Flex：弹性布局，兼容性较差（IE10+）
* Grid：网格布局，兼容性更差
* Columns：栅格系统，往往需要依赖于某个UI库，如bootstrap

### CSS3 Media Query
利用CSS3 Media Query可以轻松实现不同屏幕宽度时切换不同的页面布局
兼容性：IE9+

目前实现CSS3 Media Query 对于IE兼容的库比较成熟的有respond.js和css3-mediaqueries-js，它们各有优劣
* respond.js（推荐）:压缩后1k，只实现了media query中最常用的min-width max-width的兼容；
* css3-mediaqueries-js:基本实现了所有css3规范中的media query特性的兼容，所以导致压缩有16k，测试反馈其性能远低于respond.js;

```html
<!-- HTML5 shiv and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
```

### CSS3 Media Query使用
使用内嵌样式时，建议将响应式代码写在对应正常样式的下面，不分开书写，以便维护
```css
// 屏幕尺寸大于 480px 时应用该规则
@media screen and (min-width: 480px) {
  .header {
    background: red;
  }
}

// 屏幕尺寸小于 800px 时应用该规则
@media screen and (max-width: 800px) {}

```
操作符：
```
and or not only
```
### 断点选择，页宽
![image](https://user-images.githubusercontent.com/14285531/33216796-6b51fb26-d170-11e7-8ad0-3d4bbbf01b21.png)
![image](https://user-images.githubusercontent.com/14285531/33216805-71030204-d170-11e7-8378-57bd6349dd06.png)
