### ISSUE TITLE
less给元素添加背景图片注意事项

### ISSUE THREAD

**Issue by Moonlightg** [Moonlightg/mb#46]
在less当中当中给元素设置背景图‘ ’是必须加的，而且变量必须是@{ 变量名 }这样的格式去书写，在@{ 变量名 }后面不允许出现@符号 否则会出现报错，因为他在编译过程中会认为你@{ 变量名 }后面的@符号是一个变量，并且检测到你的变量未规范书写URL里面的要求。所以使用less在给元素添加背景图设置URL时安装下面这个写法就可以完美实现无报错
```css
background-image: url('../img/@{img_url}2x.png');
```
### 编写统一函数
```css
.bg-image(@ele_url){
  background-image: url('../img/@{img_url}2x.png');
  @media (-webkit-min-device-pixel-ratio: 3),(min-device-pixel-ratio: 3){
    background-image: url('../img/@{img_url}3x.png');
  }
}
```
### 使用
```css
.invoice{
  .bg-image('invoice')
}
```
### 生成
```css
.invoice{
  background-image: url('../img/invoice2x.png');
}
```
